### ISSUE TITLE
Redmine 4 Rails 5 support

### ISSUE THREAD

**Issue by BezQ** [iymaltsev/access_tickets#4]
I has try to install Access tickets plugin for redmine 4 .1 and Rails 5.2 and have error:
undefined method `attr_accessible' for #<Class:0x00563d053c6ca0> 

I read that reason of this error is using strong parameters instead mass assigment from Rails 4.

I'm not specialist in Rails and my question is if I'll change model and controllers clases to use accepts_nested_attributes_for your plugin will works with Rails 5.2 and redmine 4.1?
